# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: vfapisls
# "service" is the name of this project. This will also be added to your AWS resource names.
service: api-sls

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 128

custom: 
  esbuild:
    target: node20
    format: esm
    minify: true
    outputFileExtension: .mjs

build:
  esbuild: false

functions:
  hello:
    handler: src/functions/hello.handler
    events:
      - httpApi:
          path: /
          method: GET    
  getUserById:
    handler: src/functions/getUserById.handler
    events:
      - httpApi:
          path: /users/{userId}
          method: GET
